spring.application.name=tarladan

# PostgreSQL ba?lant?s?
spring.datasource.url=jdbc:postgresql://db:5432/tarladan
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate ayarlar?
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Redis
spring.data.redis.host=redis
spring.data.redis.port=6379

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kocberra3@gmail.com
spring.mail.password=grnv mpsz qpnb gudw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


logging.level.root=WARN