spring.application.name=tarladan

spring.datasource.url=jdbc:postgresql://db:5432/tarladan
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.data.redis.host=redis
spring.data.redis.port=6379

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kocberra3@gmail.com
spring.mail.password=grnv mpsz qpnb gudw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


logging.level.root=WARN

jwt.secret-key=superSecretKeyThatShouldBeAtLeast256BitsLongAndUnique
jwt.access-token-ttl-minutes=2
jwt.refresh-token-ttl-days=1